version: "3.8"

services:
    laravel-app-two:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app-two
        restart: unless-stopped
        environment:
            - APP_ENV=${APP_ENV:-production}
            - APP_DEBUG=${APP_DEBUG:-false}
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=${DB_CONNECTION:-pgsql}
            - DB_HOST=${DB_HOST:-postgres}
            - DB_PORT=${DB_PORT:-5432}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - postgres
            - redis
        env_file:
            - /var/www/html/laravel-app-two/.env
        volumes:
            - /var/www/html/laravel-app-two:/var/www
            - /var/www/html/laravel-app-two/storage:/var/www/storage
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/www/html/laravel-app-two:/var/www
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - /etc/letsencrypt/live/testiranje.de-0001/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
            - /etc/letsencrypt/live/testiranje.de-0001/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
        depends_on:
            - laravel-app-two
        networks:
            - app-network

    postgres:
        image: postgres:13
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
