name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main
      - development
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Copy .env file
        run: |
          if [ ! -f .env ]; then
            echo "Error: .env file not found in the repository."
            exit 1
          fi

      - name: Set Environment Variables
        run: |
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Copy repository to server
        run: |
          rsync -avz --delete --exclude='.git' --exclude='node_modules' --exclude='vendor' ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/laravel-app-two/

      - name: Install Composer dependencies
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            cd /var/www/html/laravel-app-two
            composer install --no-dev --optimize-autoloader
          "

      - name: Set correct permissions
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            cd /var/www/html/laravel-app-two
            sudo chown -R www-data:www-data .
            sudo chmod -R 755 .
            sudo chmod -R 775 storage bootstrap/cache
          "

      - name: Deploy and start containers
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            cd /var/www/html/laravel-app-two
            docker-compose down --volumes --remove-orphans
            docker network prune -f
            docker system prune -af --volumes
            docker network create laravel-app-two_app-network || true
            docker-compose up -d --build --force-recreate
          "

      - name: Run Laravel commands
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            cd /var/www/html/laravel-app-two
            docker-compose exec -T laravel-app-two php artisan migrate --force
            docker-compose exec -T laravel-app-two php artisan config:cache
            docker-compose exec -T laravel-app-two php artisan route:cache
            docker-compose exec -T laravel-app-two php artisan view:cache
          "

      - name: Update GitHub-specific variables
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            cd /var/www/html/laravel-app-two
            echo 'GITHUB_SHA=${{ github.sha }}' >> .env
            echo 'GITHUB_REF=${{ github.ref }}' >> .env
          "
